# Generated by Django 5.2.4 on 2025-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_case_assigned_to_alter_case_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='progress_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
