# Generated by Django 5.2.4 on 2025-07-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_case_progress_notes_case_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Waiting for Info', 'Waiting for Info'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
    ]
