# Generated by Django 5.2.4 on 2025-07-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_case_updated_at_alter_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.RemoveField(
            model_name='case',
            name='priority',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
