# Generated by Django 5.2.4 on 2025-07-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_historicalcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casehistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_history', to='cases.case'),
        ),
    ]
